spring.application.name=Banking
spring.datasource.url=jdbc:mysql://localhost:3306/Banking?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

jwt.secret="9f8d6a2c4b1e7f903c5a8d1f6b2e9c7a4f0d8e1b6c9a3f7d5e2c8a1f4b6d9e7c"
jwt.expiration=3600000

logging.level.root=INFO
logging.level.org.springframework.security=DEBUG

logging.level.org.hibernate=DEBUG
logging.level.org.springframework.orm=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
